apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: metadata-pod
  template:
    metadata:
      labels:
        app: metadata-pod
    spec:
      containers:
        - name: metadata
          image: sunitparekh/metadata:v2.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: metadata-config
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 3
