apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-state
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-pod
  serviceName: "mongo-svc"
  template:
    metadata:
      labels:
        app: mongo-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-pod
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 250Mi